# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, developer ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
    version:
      description: 'Application version'
      required: true
      
    deploy_it:
      description: 'Deploy it'
      required: false
      default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        fastlane tests
    
  deploy:
      runs-on: self-hosted
      needs: tests
      if: ${{ github.event.inputs.deploy_it == 'true' }}
      steps:
      - name: deploy packages
      - uses: actions/checkout@v1
        run: |
          echo "Deploying packages"
        
